## This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
## For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#
name: Deploy to Zerothon Page

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: node.js 패키지 installation
              run: npm ci
            - name: 사이트 빌드
              run: npm run build
            - name: git config 이메일 변경
              run: git config --global user.email "oht222@naver.com"
            - name: git config 이름 변경
              run: git config --global user.name "HyunTaek5"

            - name: 디랙토리 이동 및 zerothon-2025.github.io 배포
              run: |
                  npm run deploy:blog-ex ${{ secrets.TOKEN }}
